inherit_gem:
  rubocop-shopify: rubocop.yml

plugins:
  - rubocop-internal_affairs
  - rubocop-performance
  - rubocop-rake
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-capybara
  - rubocop-factory_bot

AllCops:
  Exclude:
    # - spec/**/*
    - spec/fixtures/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb


Layout/LineLength:
  Max: 140
  Exclude:
    - Gemfile
    - config/**/*
    - spec/factories/**/*
    - spec/fixtures/**/*


Metrics/AbcSize:
  Exclude:
    - db/**/*
    - lib/**/*


Metrics/BlockLength:
  Enabled: false


Metrics/ClassLength:
  Max: 100


Metrics/MethodLength:
  Max: 12
  Exclude:
    - db/**/* 