# frozen_string_literal: true

class CreatePlayerSnapshots < ActiveRecord::Migration[8.0]
  def change
    create_table(:player_snapshots) do |t|
      t.references(:player, null: false, foreign_key: true)
      t.date(:snapshot_date)
      t.integer(:att_cor)
      t.integer(:att_cro)
      t.integer(:att_dri)
      t.integer(:att_fin)
      t.integer(:att_fir)
      t.integer(:att_fre)
      t.integer(:att_hea)
      t.integer(:att_lon)
      t.integer(:att_lth)
      t.integer(:att_mar)
      t.integer(:att_pas)
      t.integer(:att_pen)
      t.integer(:att_tck)
      t.integer(:att_tec)
      t.integer(:att_agg)
      t.integer(:att_ant)
      t.integer(:att_bra)
      t.integer(:att_cmp)
      t.integer(:att_cnt)
      t.integer(:att_dec)
      t.integer(:att_det)
      t.integer(:att_fla)
      t.integer(:att_ldr)
      t.integer(:att_otb)
      t.integer(:att_pos)
      t.integer(:att_tea)
      t.integer(:att_vis)
      t.integer(:att_wor)
      t.integer(:att_acc)
      t.integer(:att_agi)
      t.integer(:att_bal)
      t.integer(:att_jum)
      t.integer(:att_nat)
      t.integer(:att_pac)
      t.integer(:att_sta)
      t.integer(:att_str)
      t.integer(:att_aer)
      t.integer(:att_cmd)
      t.integer(:att_com)
      t.integer(:att_ecc)
      t.integer(:att_han)
      t.integer(:att_kic)
      t.integer(:att_1v1)
      t.integer(:att_pun)
      t.integer(:att_ref)
      t.integer(:att_tro)
      t.integer(:att_thr)

      t.timestamps
    end
  end
end
